import 'dart:convert';

import 'generated_file.dart';

/// Writes `lib/main_<flavor>.dart` for each flavor.
///
/// Fully-managed, but only ever *created*: the writer refuses to overwrite an
/// entrypoint the user has edited, and an entrypoint is the most likely file in
/// this set to contain real code.
class DartEntrypointGenerator extends Generator {
  const DartEntrypointGenerator();

  @override
  String get name => 'entrypoints';

  @override
  String get description => 'A Dart entrypoint per flavor.';

  /// The shared bootstrap every generated entrypoint delegates to.
  static const String commonPath = 'lib/main_common.dart';

  /// `lib/main_<flavor>.dart`, and nothing else in `lib/`.
  ///
  /// `main.dart` is the project's own and `main_common.dart` is create-once
  /// scaffolding holding the user's setup: neither is ever taxiway's to
  /// remove, whatever the lock says.
  static final RegExp _entrypointPattern = RegExp(r'^lib/main_[^/]+\.dart$');

  @override
  bool owns(String path) =>
      path != commonPath && _entrypointPattern.hasMatch(path);

  @override
  List<GeneratedFile> render(ResolvedApp app) {
    if (!app.hasFlavors) return const <GeneratedFile>[];
    return <GeneratedFile>[
      // Created once so the entrypoints below compile on a fresh project, then
      // never touched again: by the second run it holds the user's own setup.
      GeneratedFile.scaffold(
        path: commonPath,
        contents: _common(),
        description: 'shared bootstrap for every flavor (yours to edit)',
      ),
      for (final flavor in app.flavors)
        GeneratedFile.full(
          path: flavor.entrypoint,
          contents: _entrypoint(flavor),
          description: 'entrypoint for ${flavor.name}',
        ),
    ];
  }

  /// A bootstrap that compiles and runs, and is obviously a placeholder.
  String _common() => '''
import 'package:flutter/material.dart';

/// Shared entrypoint for every flavor.
///
/// taxiway created this file once and will not modify it again — this is where
/// your app setup belongs. Each `main_<flavor>.dart` calls it with its own
/// flavor name.
Future<void> bootstrap({required String flavor}) async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(FlavorPlaceholder(flavor: flavor));
}

/// Replace this with your real app widget.
class FlavorPlaceholder extends StatelessWidget {
  const FlavorPlaceholder({required this.flavor, super.key});

  final String flavor;

  @override
  Widget build(BuildContext context) => MaterialApp(
        home: Scaffold(
          body: Center(child: Text('Running the \$flavor flavor')),
        ),
      );
}
''';

  /// A deliberately thin entrypoint.
  ///
  /// It delegates to `main_common.dart` rather than containing app setup,
  /// because taxiway owns this file and would otherwise be overwriting real
  /// code every time the config changes.
  String _entrypoint(ResolvedFlavor flavor) {
    final buffer = StringBuffer()
      ..writeln("import 'main_common.dart' as common;")
      ..writeln()
      ..writeln('/// Entrypoint for the `${flavor.name}` flavor.')
      ..writeln('///')
      ..writeln(
        '/// Generated by taxiway. Put shared setup in '
        '`main_common.dart`;',
      )
      ..writeln(
        '/// anything written here is replaced when the config '
        'changes.',
      )
      ..writeln('void main() {')
      ..writeln("  common.bootstrap(flavor: '${flavor.name}');")
      ..write('}');
    return buffer.toString();
  }
}

/// Writes `dart_defines/<flavor>.json` for flavors that declare defines.
///
/// Passed to `--dart-define-from-file`, which is why the file is a flat map of
/// strings: Flutter rejects nested values there.
class DartDefinesGenerator extends Generator {
  const DartDefinesGenerator();

  @override
  String get name => 'dart-defines';

  @override
  bool owns(String path) =>
      RegExp(r'^dart_defines/[^/]+\.json$').hasMatch(path);

  @override
  String get description => 'A dart-define file per flavor that declares one.';

  @override
  List<GeneratedFile> render(ResolvedApp app) => <GeneratedFile>[
    for (final flavor in app.flavors)
      if (flavor.dartDefines.isNotEmpty)
        GeneratedFile.full(
          path: 'dart_defines/${flavor.name}.json',
          contents: _json(flavor.dartDefines),
          description:
              '${flavor.dartDefines.length} define'
              '${flavor.dartDefines.length == 1 ? '' : 's'} for '
              '${flavor.name}',
        ),
  ];

  /// Keys sorted so regenerating produces no diff when nothing changed.
  String _json(Map<String, String> defines) {
    final sorted = <String, String>{
      for (final key in defines.keys.toList()..sort()) key: defines[key]!,
    };
    return const JsonEncoder.withIndent('  ').convert(sorted);
  }
}

/// Keeps secret-bearing paths out of version control.
///
/// Block-managed and appended: a project's `.gitignore` is entirely the user's,
/// and taxiway adds one clearly-marked region to it.
class GitignoreGenerator extends Generator {
  const GitignoreGenerator();

  @override
  String get name => 'gitignore';

  @override
  String get description => 'Ignore rules for secret-bearing files.';

  /// Everything that can hold a credential, plus taxiway's own scratch state.
  ///
  /// `.taxiway/lock.json` is deliberately absent: ownership is a team-wide fact
  /// and must be committed, or a teammate inherits no permissions.
  static const List<String> patterns = <String>[
    '.env',
    '.env.*',
    '!.env*.example',
    '*.p8',
    '*.jks',
    '*.keystore',
    '**/key.properties',
    '**/service-account*.json',
    '**/google_service_account.json',
    '.taxiway/runs/',
    '.taxiway/backups/',
    '.taxiway/run.lock',
  ];

  @override
  List<GeneratedFile> render(ResolvedApp app) => <GeneratedFile>[
    GeneratedFile.block(
      path: '.gitignore',
      contents: patterns.join('\n'),
      description: 'ignore rules for keys, keystores and .env files',
    ),
  ];
}
