import 'dart:convert';

import 'generated_file.dart';

/// Writes `lib/main_<flavor>.dart` for each flavor.
///
/// Fully-managed, but only ever *created*: the writer refuses to overwrite an
/// entrypoint the user has edited, and an entrypoint is the most likely file in
/// this set to contain real code.
class DartEntrypointGenerator implements Generator {
  const DartEntrypointGenerator();

  @override
  String get name => 'entrypoints';

  @override
  String get description => 'A Dart entrypoint per flavor.';

  @override
  List<GeneratedFile> render(ResolvedApp app) => <GeneratedFile>[
    for (final flavor in app.flavors)
      GeneratedFile.full(
        path: flavor.entrypoint,
        contents: _entrypoint(flavor),
        description: 'entrypoint for ${flavor.name}',
      ),
  ];

  /// A deliberately thin entrypoint.
  ///
  /// It delegates to `main_common.dart` rather than containing app setup,
  /// because taxiway owns this file and would otherwise be overwriting real
  /// code every time the config changes.
  String _entrypoint(ResolvedFlavor flavor) {
    final buffer = StringBuffer()
      ..writeln("import 'main_common.dart' as common;")
      ..writeln()
      ..writeln('/// Entrypoint for the `${flavor.name}` flavor.')
      ..writeln('///')
      ..writeln(
        '/// Generated by taxiway. Put shared setup in '
        '`main_common.dart`;',
      )
      ..writeln(
        '/// anything written here is replaced when the config '
        'changes.',
      )
      ..writeln('void main() {')
      ..writeln("  common.bootstrap(flavor: '${flavor.name}');")
      ..write('}');
    return buffer.toString();
  }
}

/// Writes `dart_defines/<flavor>.json` for flavors that declare defines.
///
/// Passed to `--dart-define-from-file`, which is why the file is a flat map of
/// strings: Flutter rejects nested values there.
class DartDefinesGenerator implements Generator {
  const DartDefinesGenerator();

  @override
  String get name => 'dart-defines';

  @override
  String get description => 'A dart-define file per flavor that declares one.';

  @override
  List<GeneratedFile> render(ResolvedApp app) => <GeneratedFile>[
    for (final flavor in app.flavors)
      if (flavor.dartDefines.isNotEmpty)
        GeneratedFile.full(
          path: 'dart_defines/${flavor.name}.json',
          contents: _json(flavor.dartDefines),
          description:
              '${flavor.dartDefines.length} define'
              '${flavor.dartDefines.length == 1 ? '' : 's'} for '
              '${flavor.name}',
        ),
  ];

  /// Keys sorted so regenerating produces no diff when nothing changed.
  String _json(Map<String, String> defines) {
    final sorted = <String, String>{
      for (final key in defines.keys.toList()..sort()) key: defines[key]!,
    };
    return const JsonEncoder.withIndent('  ').convert(sorted);
  }
}

/// Keeps secret-bearing paths out of version control.
///
/// Block-managed and appended: a project's `.gitignore` is entirely the user's,
/// and taxiway adds one clearly-marked region to it.
class GitignoreGenerator implements Generator {
  const GitignoreGenerator();

  @override
  String get name => 'gitignore';

  @override
  String get description => 'Ignore rules for secret-bearing files.';

  /// Everything that can hold a credential, plus taxiway's own scratch state.
  ///
  /// `.taxiway/lock.json` is deliberately absent: ownership is a team-wide fact
  /// and must be committed, or a teammate inherits no permissions.
  static const List<String> patterns = <String>[
    '.env',
    '.env.*',
    '!.env*.example',
    '*.p8',
    '*.jks',
    '*.keystore',
    '**/key.properties',
    '**/service-account*.json',
    '**/google_service_account.json',
    '.taxiway/runs/',
    '.taxiway/backups/',
    '.taxiway/run.lock',
  ];

  @override
  List<GeneratedFile> render(ResolvedApp app) => <GeneratedFile>[
    GeneratedFile.block(
      path: '.gitignore',
      contents: patterns.join('\n'),
      description: 'ignore rules for keys, keystores and .env files',
    ),
  ];
}
