import '../core/config/taxiway_config.dart';
import '../core/toolchain/fastlane_pins.dart';
import 'generated_file.dart';

/// Writes `ios/Gemfile` and `android/Gemfile`.
///
/// Two Gemfiles rather than one at the root, because fastlane resolves its
/// `fastlane/` directory relative to the working directory, and each platform
/// is run from its own.
///
/// Each one `eval_gemfile`s its `fastlane/Pluginfile`, which is the mechanism
/// `fastlane add_plugin` itself uses. Listing a plugin in the Pluginfile and
/// separately in the Gemfile makes the two drift; listing it only in the
/// Pluginfile without the eval makes fastlane report that plugins "couldn't be
/// loaded" and carry on without them.
class GemfileGenerator implements Generator {
  const GemfileGenerator();

  @override
  String get name => 'gemfiles';

  @override
  String get description => 'A pinned Gemfile per platform.';

  @override
  List<GeneratedFile> render(ResolvedApp app) => <GeneratedFile>[
    for (final platform in const <String>['ios', 'android'])
      GeneratedFile.full(
        path: '$platform/Gemfile',
        contents: _render(),
        description: 'pinned fastlane for $platform',
      ),
  ];

  String _render() =>
      '''
# Generated by taxiway. Edit taxiway.yaml and re-run `taxiway generate`
# instead of changing this file.
#
# Always run fastlane as `bundle exec fastlane`. A bare `fastlane` uses
# whatever version happens to be on PATH, which is how a lane that worked
# yesterday signs differently today.
source "https://rubygems.org"

ruby ">= ${FastlanePins.rubyFloor}"

gem "fastlane", "${FastlanePins.fastlane}"

# The Pluginfile is the single source of truth for plugins, exactly as
# `fastlane add_plugin` maintains it.
plugins_path = File.join(File.dirname(__FILE__), "fastlane", "Pluginfile")
eval_gemfile(plugins_path) if File.exist?(plugins_path)
''';
}

/// Writes the `Pluginfile` fastlane reads alongside the Gemfile.
class PluginfileGenerator implements Generator {
  const PluginfileGenerator();

  @override
  String get name => 'pluginfiles';

  @override
  String get description => 'The fastlane Pluginfile per platform.';

  @override
  List<GeneratedFile> render(ResolvedApp app) => <GeneratedFile>[
    for (final platform in const <String>['ios', 'android'])
      GeneratedFile.full(
        path: '$platform/fastlane/Pluginfile',
        contents: _render(),
        description: 'fastlane plugins for $platform',
      ),
  ];

  String _render() =>
      '''
# Generated by taxiway. Edit taxiway.yaml and re-run `taxiway generate`
# instead of changing this file.
gem "fastlane-plugin-firebase_app_distribution", "${FastlanePins.firebaseAppDistribution}"
''';
}

/// Writes `ios/fastlane/Appfile`.
///
/// Every value is read from the environment. The team id is the one exception
/// and is still not a secret — it is printed in every build log — but it is
/// defaulted from the config so an unconfigured machine still resolves.
class AppfileGenerator implements Generator {
  const AppfileGenerator();

  @override
  String get name => 'appfiles';

  @override
  String get description => 'The fastlane Appfile per platform.';

  @override
  List<GeneratedFile> render(ResolvedApp app) {
    final files = <GeneratedFile>[
      GeneratedFile.full(
        path: 'ios/fastlane/Appfile',
        contents: _ios(app),
        description: 'iOS fastlane identity',
      ),
    ];
    final android = app.androidApplicationId;
    if (android != null) {
      files.add(
        GeneratedFile.full(
          path: 'android/fastlane/Appfile',
          contents: _android(android),
          description: 'Android fastlane identity',
        ),
      );
    }
    return files;
  }

  String _ios(ResolvedApp app) {
    final team = app.iosTeamId;
    return '''
# Generated by taxiway. Edit taxiway.yaml and re-run `taxiway generate`
# instead of changing this file.
#
# Nothing here is a secret, and nothing here may become one: every value is
# read from the environment.
apple_id(ENV["FASTLANE_APPLE_ID"]) unless ENV["FASTLANE_APPLE_ID"].to_s.empty?
itc_team_id(ENV["APP_STORE_CONNECT_TEAM_ID"]) unless ENV["APP_STORE_CONNECT_TEAM_ID"].to_s.empty?
${team == null ? 'team_id(ENV["DEVELOPER_PORTAL_TEAM_ID"]) unless ENV["DEVELOPER_PORTAL_TEAM_ID"].to_s.empty?' : 'team_id(ENV.fetch("DEVELOPER_PORTAL_TEAM_ID", "$team"))'}
''';
  }

  String _android(String packageName) =>
      '''
# Generated by taxiway. Edit taxiway.yaml and re-run `taxiway generate`
# instead of changing this file.
json_key_file(ENV["PLAY_SERVICE_ACCOUNT_JSON_PATH"].to_s)
package_name("$packageName")
''';
}

/// Writes `ios/fastlane/Matchfile`.
class MatchfileGenerator implements Generator {
  const MatchfileGenerator();

  @override
  String get name => 'matchfile';

  @override
  String get description => 'The match configuration for iOS signing.';

  @override
  List<GeneratedFile> render(ResolvedApp app) {
    // Without a repo to sync against there is nothing to configure, and an
    // empty Matchfile is worse than none: it makes `match` look set up.
    if (app.matchGitUrl == null) return const <GeneratedFile>[];

    final identifiers = <String>[
      for (final flavor in app.flavors)
        if (flavor.iosBundleId != null) flavor.iosBundleId!,
    ];
    final list = identifiers.isEmpty
        ? (app.iosBundleId == null ? <String>[] : <String>[app.iosBundleId!])
        : identifiers;

    return <GeneratedFile>[
      GeneratedFile.full(
        path: 'ios/fastlane/Matchfile',
        contents:
            '''
# Generated by taxiway. Edit taxiway.yaml and re-run `taxiway generate`
# instead of changing this file.
git_url(ENV.fetch("MATCH_GIT_URL", "${app.matchGitUrl}"))
git_branch(ENV.fetch("MATCH_GIT_BRANCH", "master"))
storage_mode("${app.matchStorage.name}")
type("appstore")

app_identifier([${list.map((i) => '"$i"').join(', ')}])
''',
        description: 'match repo and bundle ids',
      ),
    ];
  }
}

/// Writes `ios/ExportOptions-<flavor>.plist`.
///
/// Only for [IosExport.flutter]. Under [IosExport.gym] the export options are
/// built in the lane from match's runtime profile mapping, and a stale plist
/// sitting next to it would be a trap.
class ExportOptionsGenerator implements Generator {
  const ExportOptionsGenerator();

  @override
  String get name => 'export-options';

  @override
  String get description =>
      'An ExportOptions plist per flavor, when Flutter does the export.';

  static String pathFor(String flavor) => 'ios/ExportOptions-$flavor.plist';

  /// The `match` profile name for a bundle id, which is fixed by match itself.
  static String matchProfileName(String bundleId) => 'match AppStore $bundleId';

  @override
  List<GeneratedFile> render(ResolvedApp app) {
    if (app.iosExport != IosExport.flutter || !app.hasFlavors) {
      return const <GeneratedFile>[];
    }
    return <GeneratedFile>[
      for (final flavor in app.flavors)
        if (flavor.iosBundleId != null)
          GeneratedFile.full(
            path: pathFor(flavor.name),
            contents: _render(app, flavor.iosBundleId!),
            description: 'export options for ${flavor.name}',
          ),
    ];
  }

  String _render(ResolvedApp app, String bundleId) {
    final team = app.iosTeamId;
    // Manual signing with an explicit profile, because automatic signing on a
    // developer laptop resolves to whatever that laptop happens to have and
    // silently produces a differently-signed build from CI.
    return '''
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by taxiway. Edit taxiway.yaml and re-run `taxiway generate`
     instead of changing this file. -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>method</key>
  <string>app-store</string>
${team == null ? '' : '  <key>teamID</key>\n  <string>$team</string>\n'}  <key>signingStyle</key>
  <string>manual</string>
  <key>provisioningProfiles</key>
  <dict>
    <key>$bundleId</key>
    <string>${matchProfileName(bundleId)}</string>
  </dict>
  <key>stripSwiftSymbols</key>
  <true/>
  <key>uploadSymbols</key>
  <true/>
</dict>
</plist>
''';
  }
}
