import 'generated_file.dart';

/// The Ruby both generated Fastfiles share.
///
/// Rendered into each platform's file rather than factored into a root
/// `Fastfile` the two import. A generated file that can be read start to finish
/// without following an include is easier to review, and taxiway rewrites both
/// together so they cannot drift.
abstract final class FastlaneRuby {
  /// The header every generated Fastfile carries.
  static String header(String platform) =>
      '''
# Generated by taxiway. Edit taxiway.yaml and re-run `taxiway generate`
# instead of changing this file.
#
# Every credential is read from ENV. If a lane below needs a value that is not
# set, it fails saying which one.

require 'shellwords'

default_platform(:$platform)
''';

  /// The `FLAVORS` table, as data rather than literals repeated in each lane.
  ///
  /// [extra] adds per-platform keys — a bundle id on iOS, a package name on
  /// Android — to the entrypoint every platform needs.
  static String flavorTable(
    ResolvedApp app,
    Map<String, String> Function(ResolvedFlavor flavor) extra,
  ) {
    final rows = <String>[
      for (final flavor in app.flavors)
        '  "${flavor.name}" => { '
            '${<String>[for (final entry in extra(flavor).entries) '${entry.key}: "${entry.value}"', 'entrypoint: "${flavor.entrypoint}"'].join(', ')} },',
    ];

    return '''
FLAVORS = {
${rows.join('\n')}
}.freeze

def flavor_config(flavor)
  FLAVORS.fetch(flavor) do
    UI.user_error!("Unknown flavor #{flavor.inspect}. Expected one of: #{FLAVORS.keys.join(', ')}")
  end
end

def require_flavor(options)
  options.fetch(:flavor) do
    UI.user_error!("Pass flavor:. Expected one of: #{FLAVORS.keys.join(', ')}")
  end
end
''';
  }

  /// Path helpers and the environment guard.
  static String helpers() => r'''
def project_root
  @project_root ||= File.expand_path("../..", __dir__)
end

def root_path(*segments)
  File.join(project_root, *segments)
end

def require_env(*names)
  missing = names.flatten.select { |name| ENV[name].to_s.strip.empty? }
  return if missing.empty?

  UI.user_error!("Missing required environment variable(s): #{missing.join(', ')}")
end

def require_file(path, hint)
  return if File.exist?(path)

  UI.user_error!("Required file not found: #{path}\n#{hint}")
end
''';

  /// One place that knows how to invoke `flutter build`.
  ///
  /// Shared because the ways of getting it wrong are silent: without
  /// `--target` Flutter compiles `lib/main.dart` under the flavor's identity,
  /// and without `--dart-define-from-file` it builds against the wrong backend.
  /// Neither fails, so neither can be caught downstream.
  static String flutterBuild() => r'''
# The dart-defines file is passed only when it exists: a flavor may
# legitimately have none, and naming a missing one fails the build.
def flutter_build(type:, flavor:, entrypoint:, extra: [])
  defines = root_path("dart_defines", "#{flavor}.json")

  args = [
    "flutter build #{type}",
    "--release",
    "--flavor #{flavor.shellescape}",
    # Never omitted. Without it Flutter builds lib/main.dart under this
    # flavor's identity: the wrong app, and the build succeeds.
    "--target #{entrypoint.shellescape}",
    *(File.exist?(defines) ? ["--dart-define-from-file #{defines.shellescape}"] : []),
    *extra
  ]

  sh("cd #{project_root.shellescape} && #{args.join(' ')}")
end
''';
}
