import '../core/config/taxiway_config.dart';
import 'generated_file.dart';

/// Writes `ios/fastlane/Fastfile`.
///
/// Whole-file managed. A Fastfile that was already in the project is never
/// touched — the writer refuses on ownership, and `taxiway adopt` is the only
/// way to hand one over — because a real Fastfile encodes a team's release
/// process and regenerating over it destroys work no test would catch.
///
/// Every value a lane needs at runtime is read from `ENV`. Nothing that could
/// be a credential is ever written into this file, and a golden test greps the
/// rendered output to keep it that way.
class IosFastfileGenerator extends Generator {
  const IosFastfileGenerator();

  @override
  String get name => 'ios-fastfile';

  @override
  String get description => 'The iOS release lanes.';

  static const String path = 'ios/fastlane/Fastfile';

  /// Where `flutter build ipa` leaves the archive, relative to the project.
  static const String archivePath = 'build/ios/archive/Runner.xcarchive';

  /// Where both export shapes are told to put the `.ipa`.
  static const String ipaDirectory = 'build/ios/ipa';

  @override
  List<GeneratedFile> render(ResolvedApp app) {
    if (!app.hasFlavors) return const <GeneratedFile>[];
    return <GeneratedFile>[
      GeneratedFile.full(
        path: path,
        contents: _render(app),
        description: 'iOS build and release lanes (${app.iosExport.name})',
      ),
    ];
  }

  String _render(ResolvedApp app) {
    final buffer = StringBuffer()
      ..writeln('# Generated by taxiway. Edit taxiway.yaml and re-run')
      ..writeln('# `taxiway generate` instead of changing this file.')
      ..writeln('#')
      ..writeln('# Every credential is read from ENV. If a lane below needs a')
      ..writeln('# value that is not set, it fails saying which one.')
      ..writeln()
      ..writeln("require 'shellwords'")
      ..writeln()
      ..writeln('default_platform(:ios)')
      ..writeln()
      ..writeln(_flavorTable(app))
      ..writeln(_helpers())
      ..writeln('platform :ios do')
      ..write(_certificatesLane(app))
      ..writeln()
      ..write(_buildLane(app))
      ..writeln()
      ..write(_testflightLane())
      ..writeln('end');
    return buffer.toString();
  }

  /// The flavor facts the lanes need, as data rather than repeated literals.
  String _flavorTable(ResolvedApp app) {
    final rows = <String>[
      for (final flavor in app.flavors)
        '  "${flavor.name}" => { '
            'bundle_id: "${flavor.iosBundleId ?? ''}", '
            'entrypoint: "${flavor.entrypoint}" },',
    ];
    return '''
FLAVORS = {
${rows.join('\n')}
}.freeze

def flavor_config(flavor)
  FLAVORS.fetch(flavor) do
    UI.user_error!("Unknown flavor #{flavor.inspect}. Expected one of: #{FLAVORS.keys.join(', ')}")
  end
end
''';
  }

  String _helpers() =>
      '''
def project_root
  @project_root ||= File.expand_path("../..", __dir__)
end

def root_path(*segments)
  File.join(project_root, *segments)
end

def require_env(*names)
  missing = names.flatten.select { |name| ENV[name].to_s.strip.empty? }
  return if missing.empty?

  UI.user_error!("Missing required environment variable(s): #{missing.join(', ')}")
end

# The exported filename is not ours to predict: Flutter names it after
# CFBundleDisplayName, so a flavor display name with a space in it lands
# verbatim, while gym names it after the product target. Globbing is the only
# thing that is right under both.
def newest_ipa
  found = Dir[root_path("$ipaDirectory", "*.ipa")].max_by { |f| File.mtime(f) }
  UI.user_error!("No .ipa found in $ipaDirectory") if found.nil?
  found
end
''';

  String _certificatesLane(ResolvedApp app) {
    final key = app.ascApiKey;
    // All three refs or none: a half-configured key cannot authenticate, and
    // rendering `ENV.fetch("null")` would fail at lane runtime with nothing
    // pointing back at the config that caused it.
    final keyIdRef = key?.keyIdRef;
    final issuerIdRef = key?.issuerIdRef;
    final p8Ref = key?.p8Ref;
    final complete = keyIdRef != null && issuerIdRef != null && p8Ref != null;
    final auth = !complete
        ? '''
  # No App Store Connect key is configured, so match authenticates
  # interactively. Add signing.ios.api_key to taxiway.yaml for unattended runs.
  private_lane :asc_api_key do
    nil
  end
'''
        : '''
  private_lane :asc_api_key do
    require_env("$keyIdRef", "$issuerIdRef", "$p8Ref")

    app_store_connect_api_key(
      key_id: ENV.fetch("$keyIdRef"),
      issuer_id: ENV.fetch("$issuerIdRef"),
      key_content: ENV.fetch("$p8Ref"),
      is_key_content_base64: true,
      in_house: false
    )
  end
''';

    return '''
$auth
  desc "Sync signing certificates and profiles via match"
  lane :certificates do |options|
    require_env("MATCH_PASSWORD")
    setup_ci if is_ci

    sync_code_signing(
      type: "appstore",
      # readonly by default: a day-to-day build must never mint a new
      # certificate, which is a limited and shared resource.
      readonly: options.fetch(:readonly, true),
      app_identifier: FLAVORS.values.map { |f| f[:bundle_id] }.reject(&:empty?),
      api_key: asc_api_key
    )
  end
''';
  }

  String _buildLane(ResolvedApp app) => switch (app.iosExport) {
    IosExport.gym => _buildLaneGym(app.iosTeamId),
    IosExport.flutter => _buildLaneFlutter(),
  };

  /// `flutter build ipa --no-codesign` archives, `gym` exports.
  ///
  /// `--no-codesign` rather than letting Flutter export and then exporting
  /// again: the second export is the one that counts, and the first costs a
  /// signing round trip and fails outright when no distribution profile is
  /// installed yet. Verified that gym signs an unsigned archive correctly.
  String _buildLaneGym(String? teamId) =>
      '''
  desc "Build a signed IPA for a flavor"
  lane :build_ipa do |options|
    flavor = options.fetch(:flavor) { UI.user_error!("Pass flavor:") }
    config = flavor_config(flavor)

    profiles = Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING] || {}
    profile = profiles[config[:bundle_id]]
    UI.user_error!("No profile synced for #{config[:bundle_id]}; run the certificates lane first.") if profile.to_s.empty?

    # Archive only. gym does the signing on export, so signing here would be
    # thrown away.
    sh("cd #{project_root.shellescape} && flutter build ipa --release --no-codesign " \\
       "--flavor #{flavor} --target #{config[:entrypoint]}")

    build_app(
      # The whole point: gym exports the archive Flutter made and does not try
      # to make one. A gym that archives a Flutter app either fails on the
      # git-ignored ios/Flutter/ephemeral, or silently builds whatever
      # Generated.xcconfig was left pointing at.
      skip_build_archive: true,
      archive_path: root_path("$archivePath"),
      output_directory: root_path("$ipaDirectory"),
      # Required even when only exporting: without it gym prompts for a scheme
      # and a non-interactive run hangs forever.
      scheme: flavor,
      # Also required, and only for this shape: an archive built with
      # --no-codesign records an empty Team, so export has none to infer and
      # fails with "exportArchive No Team Found in Archive".
      export_team_id: ${teamId == null ? 'ENV.fetch("DEVELOPER_PORTAL_TEAM_ID")' : 'ENV.fetch("DEVELOPER_PORTAL_TEAM_ID", "$teamId")'},
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { config[:bundle_id] => profile }
      }
    )

    newest_ipa
  end
''';

  /// `flutter build ipa --export-options-plist` does both legs.
  String _buildLaneFlutter() => '''
  desc "Build a signed IPA for a flavor"
  lane :build_ipa do |options|
    flavor = options.fetch(:flavor) { UI.user_error!("Pass flavor:") }
    config = flavor_config(flavor)

    plist = root_path("ios", "ExportOptions-#{flavor}.plist")
    UI.user_error!("Missing #{plist}; run `taxiway generate`.") unless File.exist?(plist)

    # Flutter archives and exports in one command, running the same
    # `xcodebuild -exportArchive` gym would.
    sh("cd #{project_root.shellescape} && flutter build ipa --release " \\
       "--flavor #{flavor} --target #{config[:entrypoint]} " \\
       "--export-options-plist=#{plist.shellescape}")

    newest_ipa
  end
''';

  String _testflightLane() => '''
  desc "Build and upload to TestFlight"
  lane :beta do |options|
    flavor = options.fetch(:flavor) { UI.user_error!("Pass flavor:") }
    config = flavor_config(flavor)

    api_key = asc_api_key
    certificates
    ipa = build_ipa(flavor: flavor)

    next UI.important("dry_run: would upload #{ipa}") if options[:dry_run]

    upload_to_testflight(
      api_key: api_key,
      app_identifier: config[:bundle_id],
      ipa: ipa,
      skip_waiting_for_build_processing: true
    )
  end
''';
}
