import 'package:xml/xml.dart';

import 'generated_file.dart';

/// Writes a shared `.xcscheme` per flavor.
///
/// Derived from the project's own `Runner.xcscheme` rather than reconstructed.
/// A scheme references its target by `BlueprintIdentifier` — a `project.pbxproj`
/// UUID — and Flutter's schemes carry a `PreActions` step that runs
/// `xcode_backend.sh prepare`. A hand-built scheme missing either of those is
/// syntactically fine and does not build, so the only safe thing to write is a
/// copy of one that already works with the build configurations swapped.
///
/// Always written to `xcshareddata/xcschemes/`, never `xcuserdata`: a per-user
/// scheme is git-ignored and works only for its author.
class IosSchemeGenerator implements Generator {
  const IosSchemeGenerator();

  @override
  String get name => 'ios-schemes';

  @override
  String get description => 'A shared Xcode scheme per flavor.';

  static const String schemeDirectory =
      'ios/Runner.xcodeproj/xcshareddata/xcschemes';

  /// Which build configuration each scheme action should point at.
  static Map<String, String> configurationsFor(String flavor) =>
      <String, String>{
        'TestAction': 'Debug-$flavor',
        'LaunchAction': 'Debug-$flavor',
        'AnalyzeAction': 'Debug-$flavor',
        'ProfileAction': 'Profile-$flavor',
        'ArchiveAction': 'Release-$flavor',
      };

  @override
  List<GeneratedFile> render(ResolvedApp app) {
    final template = app.iosSchemeTemplate;
    if (template == null || !app.hasFlavors) return const <GeneratedFile>[];

    final files = <GeneratedFile>[];
    for (final flavor in app.flavors) {
      final scheme = rewrite(template, flavor.name);
      if (scheme == null) continue;
      files.add(
        GeneratedFile.full(
          path: '$schemeDirectory/${flavor.name}.xcscheme',
          contents: scheme,
          description: 'shared scheme for ${flavor.name}',
        ),
      );
    }
    return files;
  }

  /// Returns [template] with every action pointed at [flavor]'s
  /// configurations, or null if the template is not parseable XML.
  static String? rewrite(String template, String flavor) {
    final XmlDocument document;
    try {
      document = XmlDocument.parse(template);
    } on XmlException {
      return null;
    }

    final wanted = configurationsFor(flavor);
    for (final entry in wanted.entries) {
      for (final element in document.rootElement.findAllElements(entry.key)) {
        element.setAttribute('buildConfiguration', entry.value);
      }
    }

    // Xcode writes attributes one per line with three-space indentation; keep
    // that shape so a diff against a hand-made scheme stays readable.
    return '${document.toXmlString(pretty: false)}\n';
  }
}

/// Writes `ios/Flutter/<flavor>.xcconfig`.
///
/// Where a flavor's identity actually lives on iOS. Build settings in
/// `project.pbxproj` can reference these, which keeps per-flavor values in a
/// reviewable text file rather than buried in a format nobody reads.
class XcconfigGenerator implements Generator {
  const XcconfigGenerator();

  @override
  String get name => 'xcconfigs';

  @override
  String get description => 'An xcconfig per flavor with its bundle id.';

  static const String directory = 'ios/Flutter';

  @override
  List<GeneratedFile> render(ResolvedApp app) {
    if (!app.hasFlavors) return const <GeneratedFile>[];

    return <GeneratedFile>[
      for (final flavor in app.flavors)
        GeneratedFile.full(
          path: '$directory/${flavor.name}.xcconfig',
          contents: _render(app, flavor),
          description: 'bundle id and display name for ${flavor.name}',
        ),
    ];
  }

  String _render(ResolvedApp app, ResolvedFlavor flavor) {
    final buffer = StringBuffer()
      ..writeln('// Generated by taxiway for the `${flavor.name}` flavor.')
      ..writeln('// Edit taxiway.yaml and re-run `taxiway generate` instead of')
      ..writeln('// changing this file.')
      ..writeln();

    final bundleId = flavor.iosBundleId;
    if (bundleId != null) {
      // Shown, not set. A target's own build settings take precedence over its
      // base configuration, so a bundle id assigned here would be silently
      // ignored and the flavor would build under the unflavored id. taxiway
      // writes the real one onto the build configuration itself.
      buffer.writeln('// PRODUCT_BUNDLE_IDENTIFIER is set on the build');
      buffer.writeln('// configuration itself, and is $bundleId.');
    }
    buffer.writeln(
      'APP_DISPLAY_NAME = ${flavor.displayNameOr(app.projectName)}',
    );
    final team = app.iosTeamId;
    if (team != null) buffer.writeln('DEVELOPMENT_TEAM = $team');

    final firebase = flavor.firebaseIos;
    if (firebase != null) {
      buffer
        ..writeln()
        ..writeln('// Read by the managed Run Script phase that copies the')
        ..writeln('// right GoogleService-Info.plist for this flavor.')
        ..writeln('TAXIWAY_FIREBASE_PLIST = $firebase');
    }

    return buffer.toString().trimRight();
  }
}
