/// The current shipway version.
///
/// Must match `version:` in `pubspec.yaml`, which a test asserts. Two copies
/// because a compiled program cannot read its own pubspec.
const String packageVersion = '0.1.0-beta.1';

/// Where the package lives, for a machine that has to install it.
///
/// Kept beside the version because the two are used together: a generated
/// workflow installs shipway from here at the tag matching [packageVersion].
/// Must agree with `repository:` in `pubspec.yaml`, which a test asserts.
const String packageRepository = 'https://github.com/shihabkandil/shipway';

/// The git tag a runner should install, or null when the running version is a
/// development build with no tag behind it.
///
/// Only `-dev` is untagged. A beta or a release candidate is published and
/// tagged like any release, so a workflow generated by one pins to it.
///
/// Naming a tag that does not resolve is worse than not pinning: the failure
/// arrives on the runner, at install time, in somebody else's repository.
String? get packageGitRef =>
    packageVersion.endsWith('-dev') ? null : 'v$packageVersion';
