import '../core/config/taxiway_config.dart';

/// Renders a [TaxiwayConfig] as `taxiway.yaml`.
///
/// Hand-written rather than a YAML serializer: an imported config is something
/// a human reads and edits immediately after, so key order, comments and
/// omission of defaults matter more than round-trip purity.
abstract final class ConfigWriter {
  static String render(
    TaxiwayConfig config, {
    required String generatedBy,
    required DateTime generatedAt,
  }) {
    final out = StringBuffer()
      ..writeln(
        '# taxiway.yaml — derived from this project by '
        '`taxiway import`.',
      )
      ..writeln(
        '# Generated by taxiway $generatedBy on '
        '${_date(generatedAt)}.',
      )
      ..writeln('#')
      ..writeln(
        '# Every `*_ref` names an environment variable or keychain '
        'key, never a value.',
      )
      ..writeln('# Review this file before running `taxiway adopt`.')
      ..writeln()
      ..writeln('version: ${config.version}')
      ..writeln('project:')
      ..writeln('  name: ${_scalar(config.project.name)}');

    if (config.project.pubspec != 'pubspec.yaml') {
      out.writeln('  pubspec: ${_scalar(config.project.pubspec)}');
    }
    if (config.project.flutterMin != null) {
      out.writeln('  flutter_min: ${_scalar(config.project.flutterMin!)}');
    }

    out
      ..writeln()
      ..writeln('apps:');
    for (final entry in config.apps.entries) {
      _writeApp(out, entry.key, entry.value);
    }

    if (config.notify.slackWebhookRef != null) {
      out
        ..writeln()
        ..writeln('notify:')
        ..writeln(
          '  slack_webhook_ref: ${_scalar(config.notify.slackWebhookRef!)}',
        );
    }

    return out.toString();
  }

  static void _writeApp(StringBuffer out, String id, AppConfig app) {
    out.writeln('  $id:');
    out.writeln('    path: ${_scalar(app.path)}');

    final android = app.android;
    if (android?.applicationId != null) {
      out
        ..writeln('    android:')
        ..writeln('      application_id: ${_scalar(android!.applicationId!)}');
    }
    final ios = app.ios;
    if (ios?.bundleId != null) {
      out
        ..writeln('    ios:')
        ..writeln('      bundle_id: ${_scalar(ios!.bundleId!)}');
    }

    if (app.flavors.isNotEmpty) {
      out.writeln('    flavors:');
      for (final entry in app.flavors.entries) {
        _writeFlavor(out, entry.key, entry.value);
      }
    }

    _writeSigning(out, app.signing);
  }

  static void _writeFlavor(StringBuffer out, String name, FlavorConfig flavor) {
    out.writeln('      $name:');
    // The empty suffix is meaningful — it is what makes a flavor the
    // unsuffixed production one — so it is written rather than omitted.
    out.writeln('        suffix: ${_scalar(flavor.suffix)}');
    if (flavor.versionNameSuffix != null) {
      out.writeln(
        '        version_name_suffix: ${_scalar(flavor.versionNameSuffix!)}',
      );
    }
    if (flavor.dimension != null) {
      out.writeln('        dimension: ${_scalar(flavor.dimension!)}');
    }
    if (flavor.displayName != null) {
      out.writeln('        display_name: ${_scalar(flavor.displayName!)}');
    }
    if (flavor.entrypoint != null) {
      out.writeln('        entrypoint: ${_scalar(flavor.entrypoint!)}');
    }
    if (flavor.dartDefines.isNotEmpty) {
      out.writeln('        dart_defines:');
      for (final define in flavor.dartDefines.entries) {
        out.writeln('          ${define.key}: ${_scalar(define.value)}');
      }
    }
    final firebase = flavor.firebase;
    if (firebase != null) {
      out.writeln('        firebase:');
      if (firebase.android != null) {
        out.writeln('          android: ${_scalar(firebase.android!)}');
      }
      if (firebase.ios != null) {
        out.writeln('          ios: ${_scalar(firebase.ios!)}');
      }
    }
  }

  static void _writeSigning(StringBuffer out, SigningConfig signing) {
    final ios = signing.ios;
    final android = signing.android;
    if (ios == null && android == null) return;

    out.writeln('    signing:');
    if (ios != null) {
      out.writeln('      ios:');
      if (ios.teamId != null) {
        out.writeln('        team_id: ${_scalar(ios.teamId!)}');
      }
      if (ios.matchGitUrl != null) {
        out
          ..writeln('        match_git_url: ${_scalar(ios.matchGitUrl!)}')
          ..writeln('        match_storage: ${ios.matchStorage.name}');
      }
      final key = ios.apiKey;
      if (key != null) {
        out.writeln('        api_key:');
        if (key.keyIdRef != null) {
          out.writeln('          key_id_ref: ${_scalar(key.keyIdRef!)}');
        }
        if (key.issuerIdRef != null) {
          out.writeln('          issuer_id_ref: ${_scalar(key.issuerIdRef!)}');
        }
        if (key.p8Ref != null) {
          out.writeln('          p8_ref: ${_scalar(key.p8Ref!)}');
        }
      }
    }
    if (android != null) {
      out.writeln('      android:');
      if (android.keystoreRef != null) {
        out.writeln('        keystore_ref: ${_scalar(android.keystoreRef!)}');
      }
      final props = android.keyProperties;
      if (props != null) {
        out.writeln('        key_properties:');
        if (props.storePasswordRef != null) {
          out.writeln(
            '          store_password_ref: ${_scalar(props.storePasswordRef!)}',
          );
        }
        if (props.keyPasswordRef != null) {
          out.writeln(
            '          key_password_ref: ${_scalar(props.keyPasswordRef!)}',
          );
        }
        out.writeln('          key_alias: ${_scalar(props.keyAlias)}');
      }
    }
  }

  /// Quotes a scalar when YAML would otherwise misread it.
  ///
  /// An empty string, a leading dot, a colon or a `#` all change meaning
  /// unquoted, and flavor suffixes are exactly the values that hit these.
  static String _scalar(String value) {
    if (value.isEmpty) return '""';
    final needsQuoting =
        RegExp(r'''^[\s#\-?:,\[\]{}&*!|>'"%@`]''').hasMatch(value) ||
        value.contains(': ') ||
        value.contains(' #') ||
        value.trim() != value ||
        const <String>[
          'true',
          'false',
          'null',
          'yes',
          'no',
          'on',
          'off',
        ].contains(value.toLowerCase()) ||
        RegExp(r'^-?\d').hasMatch(value);
    if (!needsQuoting) return value;
    return '"${value.replaceAll(r'\', r'\\').replaceAll('"', r'\"')}"';
  }

  static String _date(DateTime date) =>
      '${date.year}-${_two(date.month)}-${_two(date.day)}';

  static String _two(int value) => value.toString().padLeft(2, '0');
}
